services:
  app:
    build: .
    volumes:
      - ./:/var/www
    container_name: mvc-php-app
    networks:
      - mvc-php

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: mvc-php-nginx
    networks:
      - mvc-php

  database:
    image: mysql:8
    volumes:
      - ./.database/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvc
    container_name: mvc-php-database
    networks:
      - mvc-php

networks:
  mvc-php:
    driver: bridge
